{
 "title": "Nginx",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "nginx container", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "nginx-server uptime",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - container_start_time_seconds{job=\"cadvisor\", instance=\"cadvisor:8080\", name=\"nginx-server\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(irate(container_cpu_usage_seconds_total{job=\"cadvisor\", instance=\"cadvisor:8080\",image!=\"\", name=\"nginx-server\"}[$__rate_interval]) * 100) ",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Cores",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(machine_cpu_cores{job=\"cadvisor\", instance=\"cadvisor:8080\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Network",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "irate(container_network_receive_bytes_total{job=\"cadvisor\", image!=\"\", name=\"nginx-server\"}[$__rate_interval])",
     "legendFormat": "receive"
    },
    {
     "expr": "irate(container_network_transmit_bytes_total{job=\"cadvisor\", image!=\"\", name=\"nginx-server\"}[$__rate_interval])",
     "legendFormat": "transmit"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "mbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(container_memory_usage_bytes{job=\"cadvisor\", instance=\"cadvisor:8080\", image!=\"\", name=\"nginx-server\"})/1024/1024",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory Available",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "machine_memory_bytes{job=\"cadvisor\", instance=\"cadvisor:8080\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Http Total Requests",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "nginx_http_requests_total{job=\"nginx-prom\", instance=\"nginx-prom-export:9113\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(irate(container_cpu_usage_seconds_total{job=\"cadvisor\", instance=\"cadvisor:8080\",image!=\"\", name=\"nginx-server\"}[$__rate_interval]) * 100) ",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "Connections",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "irate(nginx_connections_accepted{job=\"nginx-prom\", instance=\"nginx-prom-export:9113\"}[$__rate_interval])",
     "legendFormat": "accepted"
    },
    {
     "expr": "nginx_connections_active{job=\"nginx-prom\", instance=\"nginx-prom-export:9113\"}",
     "legendFormat": "active"
    },
    {
     "expr": "irate(nginx_connections_handled{job=\"nginx-prom\", instance=\"nginx-prom-export:9113\"}[$__rate_interval])",
     "legendFormat": "handled"
    },
    {
     "expr": "irate(nginx_connections_reading{job=\"nginx-prom\", instance=\"nginx-prom-export:9113\"}[$__rate_interval])",
     "legendFormat": "reading"
    },
    {
     "expr": "irate(nginx_connections_waiting{job=\"nginx-prom\", instance=\"nginx-prom-export:9113\"}[$__rate_interval])",
     "legendFormat": "waiting"
    },
    {
     "expr": "irate(nginx_connections_writing{job=\"nginx-prom\", instance=\"nginx-prom-export:9113\"}[$__rate_interval])",
     "legendFormat": "writing"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "container_memory_usage_bytes{job=\"cadvisor\", instance=\"cadvisor:8080\", name=\"nginx-server\"}",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "Disk I/O",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "rate(container_fs_reads_total{job=\"cadvisor\", image!=\"\", name=\"nginx-server\"}[$__rate_interval])",
     "legendFormat": "read"
    },
    {
     "expr": "rate(container_fs_writes_total{job=\"cadvisor\", image!=\"\", name=\"nginx-server\"}[$__rate_interval])",
     "legendFormat": "write"
    }
   ]
  },
  { "title": "Host", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 } },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_time_seconds{job=\"node-exporter\", instance=\"node-exporter:9100\"} - node_boot_time_seconds{job=\"node-exporter\", instance=\"node-exporter:9100\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Running containers",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 5, "y": 27 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(container_last_seen{job=\"cadvisor\", instance=\"cadvisor:8080\", image!=\"\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 9, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(avg without(cpu) (irate(node_cpu_seconds_total{job=\"node-exporter\", instance=\"node-exporter:9100\", mode!=\"idle\"}[$__rate_interval]))) *100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 14, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{job=\"node-exporter\", instance=\"node-exporter:9100\"} - node_memory_MemFree_bytes{job=\"node-exporter\", instance=\"node-exporter:9100\"} - node_memory_Cached_bytes{job=\"node-exporter\", instance=\"node-exporter:9100\"} - node_memory_Buffers_bytes{job=\"node-exporter\", instance=\"node-exporter:9100\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory Available",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 19, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{job=\"node-exporter\", instance=\"node-exporter:9100\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU (host)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "avg without(cpu) (irate(node_cpu_seconds_total{job=\"node-exporter\", instance=\"node-exporter:9100\", mode!=\"idle\"}[$__rate_interval]))",
     "legendFormat": "{{mode}}"
    }
   ]
  },
  {
   "title": "Memory (host)",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{job=\"node-exporter\", instance=\"node-exporter:9100\"} - node_memory_MemFree_bytes{job=\"node-exporter\", instance=\"node-exporter:9100\"} - node_memory_Cached_bytes{job=\"node-exporter\", instance=\"node-exporter:9100\"} - node_memory_Buffers_bytes{job=\"node-exporter\", instance=\"node-exporter:9100\"}",
     "legendFormat": "used"
    },
    {
     "expr": "node_memory_Buffers_bytes{job=\"node-exporter\", instance=\"node-exporter:9100\"}",
     "legendFormat": "buffers"
    },
    {
     "expr": "node_memory_Cached_bytes{job=\"node-exporter\", instance=\"node-exporter:9100\"}",
     "legendFormat": "cached"
    },
    {
     "expr": "node_memory_MemFree_bytes{job=\"node-exporter\", instance=\"node-exporter:9100\"}",
     "legendFormat": "free"
    }
   ]
  }
 ]
}