services:
  server:
    build: .
    container_name: nginx-server
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
      - ./selfsigned.crt:/etc/ssl/certs/selfsigned.crt
      - ./selfsigned.key:/etc/ssl/private/selfsigned.key
      - ./dhparam.pem:/etc/ssl/certs/dhparam.pem
    networks:
      - monitoring

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      GF_DASHBOARDS_DEFAULT_HOME_DASHBOARD_PATH: "/var/lib/grafana/dashboards/dashboard.json"
    volumes:
      - grafana-data:/var/lib/grafana
      - ./provisioning:/etc/grafana/provisioning
      - ./dashboard.json:/var/lib/grafana/dashboards/dashboard.json
    networks:
      - monitoring

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./selfsigned.crt:/etc/ssl/certs/selfsigned.crt
      - ./selfsigned.key:/etc/ssl/private/selfsigned.key
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus-data:/prometheus
    networks:
      - monitoring

  nginx-prometheus-exporter:
    image: nginx/nginx-prometheus-exporter
    container_name: nginx-prom-export
    command:
      - "-nginx.scrape-uri=http://nginx-server:80/metrics"
    ports:
      - "9113:9113"
    networks:
      - monitoring

  node_exporter:
    image: prom/node-exporter
    container_name: node-exporter
    command:
      - "--path.rootfs=/host"
    pid: host
    volumes:
      - "/:/host:ro"
    ports:
      - "9100:9100"
    networks:
      - monitoring

  cadvisor:
    image: gcr.io/cadvisor/cadvisor
    container_name: cadvisor
    ports:
      - "8080:8080"
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    devices:
      - /dev/kmsg
    networks:
      - monitoring

volumes:
  grafana-data:
  prometheus-data:

networks:
  monitoring:
    name: monitoring
